In [35]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.datasets import load_iris

In [36]:
iris = load_iris()

In [37]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [38]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [39]:
model_log = LogisticRegression(max_iter=5000)
model_log.fit(X_train, y_train)
model_log.score(X_test, y_test)

1.0

In [40]:
model_dtree= DecisionTreeClassifier()
model_dtree.fit(X_train, y_train)
model_dtree.score(X_test, y_test)

1.0

In [41]:
model_svm = SVC()
model_svm.fit(X_train, y_train)
model_svm.score(X_test, y_test)

1.0

In [42]:
model_rf = RandomForestClassifier()
model_rf.fit(X_train, y_train)
model_rf.score(X_test, y_test)

1.0

In [43]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [44]:
for train_index, test_index in kf.split([5,6,7,8,9,10,11,12,13]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [45]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [46]:
score_log = get_score(LogisticRegression(max_iter=5000), X_train, X_test, y_train, y_test )
score_log

1.0

In [47]:
score_dtree = get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test )
score_dtree

1.0

In [48]:
score_svm = get_score(SVC(), X_train, X_test, y_train, y_test )
score_svm

1.0

In [49]:
score_rf = get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test )
score_rf

1.0

In [50]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [51]:
score_log = []
score_dtree = []
score_svm = []
score_rf =[]

for train_index, test_index in kf.split(iris.data):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]
    print(get_score(LogisticRegression(max_iter=5000), X_train, X_test, y_train, y_test))
    print(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
    print(get_score(SVC(), X_train, X_test, y_train, y_test))
    print(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [52]:
score_log = []
score_dtree = []
score_svm = []
score_rf =[]

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    print(get_score(LogisticRegression(max_iter=5000), X_train, X_test, y_train, y_test))
    print(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
    print(get_score(SVC(), X_train, X_test, y_train, y_test))
    print(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

NameError: name 'digits' is not defined

In [53]:
score_log = []
score_dtree = []
score_svm = []
score_rf =[]

for train_index, test_index in folds.split(iris.data, iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]
    score_log.append(get_score(LogisticRegression(max_iter=5000), X_train, X_test, y_train, y_test))
    score_dtree.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [54]:
score_log
np.array(score_log).mean()

0.9733333333333333

In [55]:
np.array(score_dtree).mean()

0.9666666666666667

In [56]:
np.array(score_svm).mean()

0.96

In [57]:
np.array(score_rf).mean()

0.9533333333333333

In [58]:
from sklearn.model_selection import cross_val_score

In [59]:
cross_val_score(LogisticRegression(max_iter=5000), iris.data, iris.target, cv=3)

array([0.98, 0.96, 0.98])

In [60]:
cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)

array([0.98, 0.92, 0.98])

In [61]:
cross_val_score(SVC(), iris.data, iris.target, cv=3)

array([0.96, 0.98, 0.94])

In [62]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=3)

array([0.98, 0.94, 0.98])

In [63]:
cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=3).mean()

0.96